@startuml
skinparam classAttributeIconSize 0
class 空車リスト {
- 管理番号:int
}
class 車 {
- 管理番号:String
- 車種:String
- 駆動方式:String
}
class 顧客 {
- 顧客ID:String
- name:String
- 電話番号:String
- 郵便番号:String
- 住所:String
---
+ setname(氏名:String) void
}
class 予約{
- 予約番号:int
- 管理番号:String
- 顧客ID:String
- 予約日:String
}
class 貸出{
- 貸出番号:String
- 管理番号:String
- 顧客ID:String
- 予約日:String


}
hide 空車リスト circle
hide 車 circle
hide 顧客 circle
hide 予約 circle
hide 貸出 circle
@enduml