@startuml
' left to right direction
actor 利用者#DDDDDD;line:black;line.bold;
actor ベ#DDDDDD;line:black;line.bold;

    usecase 電源SW
    usecase ライントレーサー
    usecase 右モータ
    usecase 左モータ
    usecase 光センサー

    利用者 -->電源SW:押す
    電源SW-->ライントレーサー:[ON]の場合起動
    電源SW-->ライントレーサー:[OFF]の場合停止
    ライントレーサー --> 光センサー
    光センサー-->右モータ:暗い[OFF]/明るい[ON]
    光センサー-->左モータ:暗い[ON]/明るい[OFF]



