@startuml ユースケース図
left to right direction
actor 利用者#DDDDDD;line:black;line.bold;
rectangle 宿泊予約 {
usecase キャンペーン価格で予約する
usecase ログイン
usecase (<u>予約完了</u>\n拡張点\nキャンペーン期間中) as input
}
input .> キャンペーン価格で予約する : <<extend>>
input .> ログイン
利用者-->input
@enduml