@startuml
' left to right direction
actor 利用者#DDDDDD;line:black;line.bold;
actor 光センサー#DDDDDD;line:black;line.bold;
actor 左右モータ#DDDDDD;line:black;line.bold;

rectangle ライントレーサー{
    usecase 電源OFF
    usecase 電源ON
    usecase ライン境界線走る
}
    利用者 -->電源ON
    利用者 -->電源OFF
    光センサー -->ライン境界線走る
    左右モータ -->ライン境界線走る
    ライン境界線走る -->電源ON 
    
    @enduml

